spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ${ES_HOST}:${ES_PORT}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hibernate.default_schema: public

springdoc:
  swagger-ui:
    path: /api/swagger
token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    plus-hour: ${ACCESS_TOKEN_HOUR}
  refresh-token:
    plus-hour: ${REFRESH_TOKEN_HOUR}

redis:
  jwt:
    host: ${REDIS_JWT_HOST}
    port: ${REDIS_JWT_PORT}

  alarm:
    host: ${REDIS_ALARM_HOST}
    port: ${REDIS_ALARM_PORT}

ocr:
  api:
    url: ${OCR_API_URL}
  secret: ${OCR_SECRET}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}