spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ${ES_HOST}:${ES_PORT}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hibernate.default_schema: public
springdoc:
  swagger-ui:
    path: /api/swagger

token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    plus-hour: ${ACCESS_TOKEN_HOUR}
  refresh-token:
    plus-hour: ${REFRESH_TOKEN_HOUR}
