name: medeasy-container-cd
on:
  push:
    branches:
      - prod

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ES_HOST: ${{secrets.ES_HOST}}
      ES_PORT: ${{secrets.ES_PORT}}
      TOKEN_SECRET_KEY: ${{secrets.TOKEN_SECRET_KEY}}
      ACCESS_TOKEN_HOUR: ${{secrets.ACCESS_TOKEN_HOUR}}
      REFRESH_TOKEN_HOUR: ${{secrets.REFRESH_TOKEN_HOUR}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}


    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.head_ref }}'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with gradlew
        run: ./gradlew clean test bootJar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: medeasy
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.MEDEASY_HOST}}
          username: ${{ secrets.MEDEASY_USERNAME }}
          key: ${{ secrets.MEDEASY_PEM }}
          script: |
            sh deploy.sh
          verbose: true

